# Generated by Django 5.1.1 on 2024-10-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('home_management', models.TextField()),
                ('warning_signs', models.TextField()),
            ],
        ),
    ]
