# Generated by Django 5.1.1 on 2024-10-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ambulance_hospital_alter_appointment_patient_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Ambulance',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
